server:
  port: 8083

spring:
  application:
    name: orders
  r2dbc:
    url: r2dbc:postgresql://database-1.ckbmcaom0bdy.us-east-1.rds.amazonaws.com:5432/arka?sslmode=require
    username: postgres
    password: dbAdm0925
    pool:
      enabled: true
      initial-size: 5
      max-size: 20

  sql:
    init:
      mode: never
logging:
  level:
    org.springframework.r2dbc: INFO
    org.springframework.data.r2dbc: INFO

app:
  cart:
    base-url: http://alb-if-arka-1265771644.us-east-1.elb.amazonaws.com
  customer:
    base-url: http://alb-if-arka-1265771644.us-east-1.elb.amazonaws.com
  inventory:
    base-url: http://alb-if-arka-1265771644.us-east-1.elb.amazonaws.com
notification:
  api:
    url: https://gqvbz9gilh.execute-api.us-east-1.amazonaws.com/send-email


