spring:
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://database-1.ckbmcaom0bdy.us-east-1.rds.amazonaws.com:5432/arka?sslMode=require}
    username: ${R2DBC_USERNAME:postgres}
    password: ${R2DBC_PASSWORD:dbAdm0925}
  application:
    name: reporte
server:
  port: 8091